Move rest functionality into django_instant_rest
zero-gravity-computer/issue-tracker-backend pull request #21
Opened 2020-10-13 16:18 UTC by craigfay

Instead of maintaining modules that deliver REST API functionality, we're relying on the [django_instant_rest](https://github.com/zero-gravity-computer/django_instant_rest) package to provide it.

Testing Steps:
* Pull the feature branch: `git fetch && git checkout use_django_instant_rest_package`
* Remove Pipenv virtual environment: `pipenv --rm`
* Run Server: `pipenv run python manage.py runserver`

Create, Read, Update, and Delete functionality should still work for all models.

2020-10-13 16:19 UTC, craigfay commented on backend/settings.py
> -    'core.middleware.access_control.AccessControl',
This middleware wasn't being used

2020-10-13 16:23 UTC, craigfay commented on core/middleware.py
> +'''
`patterns.resource()` can accept [django style middleware](https://docs.djangoproject.com/en/3.1/topics/http/middleware/). This is helpful if we want to modify just one url route.

2020-10-14 15:17 UTC, J4mesB4xter requested changes
this seems to say your pull request would delete almost 400 lines of code i dont remember discussing-- I'm probably reading it wrong but just in case this is an error I'm goin to request a change so we can talk it out before merging this with the master branch.

sorry for wasting your time if this is a user issue!

2021-01-22 04:49 UTC, J4mesB4xter approved these changes

2021-01-22 04:49 UTC, merged